#!/bin/bash

# it was generated by a Junie idk whether it works or not :)

# Define constants
DOTFILES_DIR=$(pwd)
CONFIG_DIR="$HOME/.config"
BACKUP_DIR="$HOME/.config_backup_$(date +%Y%m%d_%H%M%S)"

# List of required packages (Arch Linux Extra/Core)
OFFICIAL_PACKAGES=(
    hyprland
    swww
    waybar
    kitty
    rofi
    nautilus
    brightnessctl
    playerctl
    wireplumber
    qt5ct
    qt6ct
    kvantum
    breeze-icons
    gsettings-desktop-schemas
)

# List of AUR packages
AUR_PACKAGES=(
    hyprshot
    adw-gtk3
)

echo "--- Hyprland Dotfiles Installer ---"

# Step 1: Install Dependencies
echo "[1/4] Checking and installing dependencies..."

# Detect AUR helper
AUR_HELPER=""
if command -v yay >/dev/null; then
    AUR_HELPER="yay"
elif command -v paru >/dev/null; then
    AUR_HELPER="paru"
fi

if command -v pacman >/dev/null; then
    echo "Installing official packages via pacman..."
    sudo pacman -S --needed --noconfirm "${OFFICIAL_PACKAGES[@]}"
    
    if [ -n "$AUR_HELPER" ]; then
        echo "Installing AUR packages via $AUR_HELPER..."
        $AUR_HELPER -S --needed --confirm=false "${AUR_PACKAGES[@]}"
    else
        echo "Warning: No AUR helper (yay/paru) found. Skipping AUR packages: ${AUR_PACKAGES[*]}"
        echo "Please install them manually or install an AUR helper first."
    fi
else
    echo "Error: This script is intended for Arch Linux (pacman not found)."
    exit 1
fi

# Step 2: Create Backup
echo "[2/4] Backing up existing configurations to $BACKUP_DIR..."
mkdir -p "$BACKUP_DIR"
for item in .config/hypr .config/waybar .config/wlogout .config/kitty; do
    if [ -d "$HOME/$item" ]; then
        mv "$HOME/$item" "$BACKUP_DIR/"
    fi
done

# Step 3: Symlink Configurations
echo "[3/4] Symlinking configurations..."
mkdir -p "$CONFIG_DIR"
ln -sf "$DOTFILES_DIR/.config/hypr" "$CONFIG_DIR/"
ln -sf "$DOTFILES_DIR/.config/waybar" "$CONFIG_DIR/"
ln -sf "$DOTFILES_DIR/.config/wlogout" "$CONFIG_DIR/"
ln -sf "$DOTFILES_DIR/.config/kitty" "$CONFIG_DIR/"

# Step 4: Initial Setup (Wallpaper)
echo "[4/4] Setting initial wallpaper..."
# Ensure swww-daemon is running
if ! pgrep -x swww-daemon >/dev/null; then
    swww-daemon &
    sleep 1
fi
swww img "$DOTFILES_DIR/backgrounds/shorekeeper.png" \
  --transition-type random \
  --transition-fps 144

echo "--- Installation Complete! ---"
echo "Note: Some changes may require a Hyprland restart (SUPER + M for logout or SUPER + Q to kill active)."
