-- Generated by quickshell/scripts/themes/change-hyprland-colors.bash.
-- Do not edit: rewritten every time the theme changes.
--
-- Theme: shorekeeper-blue
--
-- Consumed by decoration.lua, which falls back to its own values if this file
-- is missing or will not load.

return {
    active_border = { "rgba(bf7ee0ff)", "rgba(5d578cff)" },
    active_border_angle = 135,
    inactive_border = "rgba(60627555)",
}
