-- Generated by quickshell/scripts/themes/change-hyprland-colors.bash.
-- Do not edit: rewritten every time the theme changes.
--
-- Theme: girls-last-tour
--
-- Consumed by decoration.lua, which falls back to its own values if this file
-- is missing or will not load.

return {
    active_border = { "rgba(d9a441ff)", "rgba(9a896fff)" },
    active_border_angle = 135,
    inactive_border = "rgba(6b645955)",
}
