#!/usr/bin/env bash
#
# Writes kitty's per-theme colour overrides from a quickshell theme, then tells
# any running kitty to reload.
#
# Only the roles a theme actually defines are written. Everything else --- the
# greens, cyans, tabs and borders --- stays in colors/base.conf, which kitty.conf
# includes before this file.
#
#     ./change-kitty-colors.bash shorekeeper-blue
#
set -euo pipefail

THEME="${1:-}"
[[ -n $THEME ]] || { echo "usage: ${0##*/} <theme-id>" >&2; exit 2; }

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# scripts/themes/ -> the quickshell config root.
QS_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd -P)"

THEME_FILE="$QS_DIR/themes/$THEME.json"
OUT="${KITTY_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/kitty}/colors/colors.conf"

command -v jq >/dev/null || { echo "change-kitty-colors: jq is not installed" >&2; exit 1; }
[[ -f $THEME_FILE ]] || { echo "change-kitty-colors: no such theme: $THEME_FILE" >&2; exit 1; }

# The theme's semantic colours, in one pass.
#
# Note which is which: `background` is "transparent" in every theme --- kitty
# gets its transparency from background_opacity in kitty.conf, so `surface` is
# the real background here. And `foreground` is the colour for text on the
# desktop, which in a dark theme is dark; `foregroundSurface` is the one meant
# to sit on a surface, so that is terminal text.
read -r SURFACE FOREGROUND ACTIVE SECONDARY DISABLED < <(
    jq -r '[
        .colors.kitty.surface,
        .colors.kitty.foreground,
        .colors.kitty.active,
        .colors.kitty.secondary,
        .colors.kitty.disabled
    ] | @tsv' "$THEME_FILE"
)

# jq yields "null" for a missing key and, worse, silently swallows one in string
# concatenation --- which is how this script used to emit `cursor` with no value
# at all. Check every colour before writing anything.
for name in SURFACE FOREGROUND ACTIVE SECONDARY DISABLED; do
    value="${!name}"
    if [[ ! $value =~ ^#[0-9a-fA-F]{6}$ ]]; then
        echo "change-kitty-colors: $THEME has no usable ${name,,} colour (got '${value}')" >&2
        exit 1
    fi
done

mkdir -p "$(dirname -- "$OUT")"

# Written to a temporary file and moved into place, so a failure half way
# through leaves the previous colours intact rather than a truncated file.
TMP="$(mktemp -- "$OUT.XXXXXX")"
trap 'rm -f -- "$TMP"' EXIT

cat > "$TMP" <<EOF
# Generated by scripts/themes/change-kitty-colors.bash --- do not edit.
# Theme: $THEME
#
# Overrides colors/base.conf. Anything not set here keeps its base value.

background            $SURFACE
foreground            $FOREGROUND

cursor                $ACTIVE
cursor_text_color     $SURFACE

selection_background  $SECONDARY
selection_foreground  $FOREGROUND

dim_foreground        $DISABLED
url_color             $ACTIVE

active_border_color   $ACTIVE
inactive_border_color $DISABLED

active_tab_background   $SECONDARY
active_tab_foreground   $FOREGROUND
inactive_tab_background $SURFACE
inactive_tab_foreground $DISABLED

# The accent takes over the magenta pair; the rest of the ANSI set is the
# base palette's, which is tuned to stay readable across themes.
color5                $ACTIVE
color13               $ACTIVE
color0                $SURFACE
color8                $SECONDARY
EOF

mv -- "$TMP" "$OUT"
trap - EXIT

# kitty re-reads its config on SIGUSR1. Without this only new windows pick the
# theme up. pkill exits 1 when nothing matches, which is not an error here.
pkill -USR1 -x kitty || true
