#!/usr/bin/env bash
#
# Recolours Hyprland's window borders from a quickshell theme.
#
# Writes hypr/modules/colors.lua so the colours survive a reload or a relogin,
# then applies them to the running compositor straight away.
#
#     ./change-hyprland-colors.bash shorekeeper-blue
#
set -euo pipefail

THEME="${1:-}"
[[ -n $THEME ]] || { echo "usage: ${0##*/} <theme-id>" >&2; exit 2; }

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
QS_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd -P)"

THEME_FILE="$QS_DIR/themes/$THEME.json"
# Alongside the quickshell config rather than under $HOME, so this works in a
# checkout that is not the installed one.
OUT="$QS_DIR/../hypr/modules/colors.lua"

# Angle of the active border gradient, matching decoration.lua's fallback.
ANGLE=135
# Inactive borders are washed out rather than a different hue.
INACTIVE_ALPHA="55"

command -v jq >/dev/null || { echo "change-hyprland-colors: jq is not installed" >&2; exit 1; }
[[ -f $THEME_FILE ]] || { echo "change-hyprland-colors: no such theme: $THEME_FILE" >&2; exit 1; }

read -r ACTIVE SECONDARY DISABLED < <(
    jq -r '[.colors.active, .colors.secondary, .colors.disabled] | @tsv' "$THEME_FILE"
)

for name in ACTIVE SECONDARY DISABLED; do
    value="${!name}"
    if [[ ! $value =~ ^#[0-9a-fA-F]{6}$ ]]; then
        echo "change-hyprland-colors: $THEME has no usable ${name,,} colour (got '${value}')" >&2
        exit 1
    fi
done

# Hyprland wants rgba(RRGGBBAA); the themes are #RRGGBB.
rgba() {
    printf 'rgba(%s%s)' "${1#\#}" "$2"
}

ACTIVE_RGBA="$(rgba "$ACTIVE" ff)"
SECONDARY_RGBA="$(rgba "$SECONDARY" ff)"
INACTIVE_RGBA="$(rgba "$DISABLED" "$INACTIVE_ALPHA")"

mkdir -p "$(dirname -- "$OUT")"

TMP="$(mktemp -- "$OUT.XXXXXX")"
trap 'rm -f -- "$TMP"' EXIT

cat > "$TMP" <<EOF
-- Generated by quickshell/scripts/themes/change-hyprland-colors.bash.
-- Do not edit: rewritten every time the theme changes.
--
-- Theme: $THEME
--
-- Consumed by decoration.lua, which falls back to its own values if this file
-- is missing or will not load.

return {
    active_border = { "$ACTIVE_RGBA", "$SECONDARY_RGBA" },
    active_border_angle = $ANGLE,
    inactive_border = "$INACTIVE_RGBA",
}
EOF

# Refuse to install a file Lua cannot load, so a bad write can never take the
# Hyprland config down with it.
if command -v luac >/dev/null && ! luac -p "$TMP" 2>/dev/null; then
    echo "change-hyprland-colors: generated colors.lua is not valid Lua, keeping the old one" >&2
    exit 1
fi

mv -- "$TMP" "$OUT"
trap - EXIT

# Apply to the running compositor. `hyprctl keyword` refuses to work under the
# Lua parser --- it tells you to use eval --- and a full `hyprctl reload` would
# re-run every bind and submap definition just to change two colours.
if command -v hyprctl >/dev/null && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
    hyprctl eval "hl.config({ general = { col = {
        active_border = { colors = { \"$ACTIVE_RGBA\", \"$SECONDARY_RGBA\" }, angle = $ANGLE },
        inactive_border = \"$INACTIVE_RGBA\",
    } } })" >/dev/null
fi
